CREATE TABLE `resume_documents` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `lead_id` int(11) NOT NULL,
  `lead_name` varchar(300) DEFAULT NULL,
  `original_resume_name` varchar(255) NOT NULL,
  `file_path` varchar(500) NOT NULL,
  `file_extension` varchar(20) DEFAULT NULL,
  `file_size` bigint(20) DEFAULT NULL,
  `file_hash` varchar(64) DEFAULT NULL,
  `extraction_status` enum('pending','completed','unsupported','missing','error') NOT NULL DEFAULT 'pending',
  `extraction_engine` varchar(50) DEFAULT NULL,
  `raw_text` longtext DEFAULT NULL,
  `extracted_name` varchar(255) DEFAULT NULL,
  `extracted_email` varchar(255) DEFAULT NULL,
  `extracted_phone` varchar(100) DEFAULT NULL,
  `extracted_skills` text DEFAULT NULL,
  `metadata_json` longtext DEFAULT NULL,
  `last_error` text DEFAULT NULL,
  `extracted_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_resume_doc_lead_file` (`lead_id`,`original_resume_name`),
  KEY `idx_resume_doc_status` (`extraction_status`),
  KEY `idx_resume_doc_file_hash` (`file_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
